### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by JaninaPi** [raspberrypilearning/username-generator#1]
Step 2, line 37: can the block type be added to `set`?

**Comment by rik-cross** [comment]
Yep, I've just updated the draft content to include this. Thanks.

**Comment by JaninaPi** [comment]
Thank you!
In step 3, the two halves of the image are technically in the wrong order — you first tick the box again, then add items to the list. Not sure whether it's worth changing that though.

**Comment by rik-cross** [comment]
Yeah, that's difficult because the image shows where the elements would be in Scratch (with the list to the right). I'll not change that now but will review if we get any feedback on this. Thanks.
